[settings]
default_target_type = "symbolic"

[helpers]

[default]
depends = []

[default.variables]
git_user_name = "Leoyzen"
git_user_email = "leoyzen@gmail.com"
# git_proxy = "socks5h://127.0.0.1:6153"  # 取消注释以启用代理

[default.files]
"config/shell/fish/fish_plugins" = "~/.config/fish/fish_plugins"
"config/shell/fish/conf.d" = "~/.config/fish/conf.d"
"config/tools/git" = { target = "~/.gitconfig", type = "template" }
"config/tools/starship.toml" = "~/.config/starship.toml"
"config/tools/tmux.conf" = "~/.tmux.conf"
"config/package-managers/uv.toml" = "~/.config/uv/uv.toml"

[rust.files]
"config/package-managers/cargo" = "~/.cargo/config.toml"
"config/linters-formatters/rustfmt.toml" = "~/.config/rustfmt/rustfmt.toml"

[python.files]
"config/package-managers/pip" = "~/.pip/pip.conf"
"config/linters-formatters/flake8" = "~/.config/flake8"
"config/linters-formatters/ruff.toml" = "~/.config/ruff/ruff.toml"
"config/linters-formatters/yapf" = "~/.config/yapf/style"

[bspm.files]
"config/package-managers/bspm" = "~/.config/blindspot/bspm.yaml"

[pier.files]
"config/package-managers/pier.toml" = "~/.config/pier/pier.toml"

[rye.files]
"config/package-managers/rye.toml" = "~/.config/rye/config.toml"

[alacritty.files]
"config/editors/terminals/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[wezterm.files]
"config/editors/terminals/wezterm.lua" = "~/.wezterm.lua"

[linuxbrew.files]
"config/shell/fish/linuxbrew.fish" = "~/.config/fish/conf.d/linuxbrew.fish"

[kitty.files]
"config/editors/terminals/kitty.conf" = "~/.config/kitty/kitty.conf"

[conda.files]
"config/package-managers/condarc" = "~/.condarc"

[helix.files]
"config/editors/helix/config.toml" = "~/.config/helix/config.toml"
"config/editors/helix/languages.toml" = "~/.config/helix/languages.toml"

[zed.files]
"config/editors/zed/keymap.json" = "~/.config/zed/keymap.json"
"config/editors/zed/settings.json" = "~/.config/zed/settings.json"

[vim.files]
"config/editors/vim/spacevim.vim" = "~/.spacevim"

[opencode.files]
"opencode/command" = "~/.config/opencode/command"
"opencode/antigravity.json" = "~/.config/opencode/antigravity.json"
"opencode/oh-my-opencode.jsonc" = "~/.config/opencode/oh-my-opencode.jsonc"
"opencode/opencode.jsonc" = "~/.config/opencode/opencode.jsonc"

[skills.files]
"skills" = "~/.config/opencode/skill"
".claude/skills" = "~/.claude/skills"
